name: playlist-sorter
services:
  backend:
    container_name: playlist-sorter-backend
    build: ./backend
    ports:
      - "8182:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    container_name: playlist-sorter-frontend
    build: ./frontend
    ports:
      - "5182:80"
    depends_on:
      - backend
